### PR TITLE
Upgrading to Next.js 12

### PR DESCRIPTION
**Pull request by ptrrdrck**
This pull request includes the upgrade of Next.js to version 12 via `npm install next@12` and package dependency fixes via `npm audit fix`.

### CODE REVIEW

**Comment by pangolin1** [comment]
looks like it works OK, but not sure why the pdf library is all up in the public dir

**Comment by pangolin1** [comment]
@Pai-Sho it seems to be something the Nextjs pdf viewer needs, but are any of those pdfs in `/public` actually being used?

**Comment by Pai-Sho** [comment]
That was a hacky solution to get the governance beigepaper up. It is live at [keeperdao.com/files](https://www.keeperdao.com/files/gov-beigepaper.pdf)

**Comment by pangolin1** [comment]
aite whatever lets ship it

**Review by pangolin1 — APPROVED** [review]

**Pull request merged**
